kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: okera-reader-role
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["services", "nodes", "pods", "pods/exec", "pods/log"]
  verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: okera-reader-role-binding
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: okera-reader-role
  apiGroup: rbac.authorization.k8s.io