# These are the default configurations that creates an insecure cluster
# out of the box. No changes should be necessary to these configs to
# get the cluster to start up.
# This puts a file with 'unauthenticated' as the contents.
apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
data:
  {{ range $index, $value := .Values.common.secret_files }}
  {{ $index }}: {{ $.Files.Get $value | b64enc }}
  {{ end }}
  {{ range $index, $value := .Values.common.secret_strings }}
  {{ $index }}: {{ $value | b64enc }}
  {{ end }}
  {{ if .Values.ssl.enabled }}
  SSL_CERTIFICATE_FILE: {{ .Files.Get .Values.ssl.secret_files.SSL_CERTIFICATE_FILE | b64enc }}
  SSL_KEY_FILE: {{ .Files.Get .Values.ssl.secret_files.SSL_KEY_FILE | b64enc }}
  {{ end }}
  {{ if .Values.jwt.enabled }}
  JWT_PUBLIC_KEY: {{ .Files.Get .Values.jwt.secret_files.JWT_PUBLIC_KEY | b64enc }}
  JWT_PRIVATE_KEY: {{ .Files.Get .Values.jwt.secret_files.JWT_PRIVATE_KEY | b64enc }}
  {{ end }}
  {{ if .Values.ldap.enabled }}
  {{ if .Values.ldap.secret_strings }}
  GROUP_RESOLVER_LDAP_PASSWORD: {{ .Values.ldap.secret_strings.GROUP_RESOLVER_LDAP_PASSWORD | b64enc }}
  LDAP_USER_QUERY_SERVICE_PASSWORD: {{ .Values.ldap.secret_strings.LDAP_USER_QUERY_SERVICE_PASSWORD | b64enc }}
  {{ end }}
  {{ if .Values.ldap.secret_files }}
  GROUP_RESOLVER_LDAP_PASSWORD: {{ .Files.Get .Values.ldap.secret_files.GROUP_RESOLVER_LDAP_PASSWORD | b64enc }}
  LDAP_USER_QUERY_SERVICE_PASSWORD: {{ .Files.Get .Values.ldap.secret_files.LDAP_USER_QUERY_SERVICE_PASSWORD | b64enc }}
  {{ end }}
  {{ end }}
  {{ if .Values.db.enabled }}
  {{ if .Values.db.secret_strings }}
  CATALOG_DB_PASSWORD: {{ .Values.db.secret_strings.CATALOG_DB_PASSWORD | b64enc }}
  {{ end }}
  {{ if .Values.db.secret_files }}
  CATALOG_DB_PASSWORD: {{ .Files.Get .Values.db.secret_files.CATALOG_DB_PASSWORD | b64enc }}
  {{ end }}
  {{ end }}