apiVersion: v1
kind: Service
metadata:
  name: canary
  labels:
    run: canary
spec:
  ports:
    # Note: services rely on the name of this port. Do not change it without changing
    # all references to it.
    - name: webport
      port: 5010
      targetPort: 5010
  selector:
    run: canary
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    run: canary
  name: canary
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      run: canary
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/02-config.yaml") . | sha256sum }}
        configHash: ""
        {{ if .Values.pod.annotations }}
        {{- .Values.pod.annotations | toYaml  | nindent 8}} 
        {{ end }}
      labels:
        run: canary
    spec:
      serviceAccountName: {{ .Values.serviceaccount.name | default "default" }}
      automountServiceAccountToken: true
      containers:
      - image: {{ .Values.image.repository }}/canary:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: canary
        ports:
        - containerPort: 5010
          protocol: TCP
        livenessProbe:
          exec:
            command:
              - /opt/health-check.py
          initialDelaySeconds: 15
          periodSeconds: 60
        readinessProbe:
          exec:
            command:
              - /opt/health-check.py
          initialDelaySeconds: 5
          periodSeconds: 5
        envFrom:
        - configMapRef:
            name: default-odas-config
        - configMapRef:
            name: odas-config
        env:
        - name: RESTART_VERSION_0
          value: "1"
        - name: WATCHER_PREFIX
          value: "canary"
        volumeMounts:
        - mountPath: /etc/secrets
          name: secrets
          readOnly: true
        - mountPath: /var/lib/okera
          name: okera-lib
        - mountPath: /var/log/okera
          name: okera-log                    
{{ if .Values.extraVolumeMounts }}
{{- .Values.extraVolumeMounts | toYaml  | nindent 8}} 
{{ end }}
      volumes:      
      - name: secrets
        secret:
          defaultMode: 420
          secretName: secrets
      - name: okera-lib
        hostPath:
          path: /var/lib/okera
          type: DirectoryOrCreate
      - name: okera-log
        hostPath:
          path: /var/log/okera
          type: DirectoryOrCreate
{{ if .Values.extraVolumes }}
{{- .Values.extraVolumes | toYaml  | nindent 6}} 
{{ end }}
      terminationGracePeriodSeconds: 5
{{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
{{- end }}