apiVersion: v1
kind: Service
metadata:
  name: cerebro-catalog
  labels:
    run: cerebro-catalog
spec:
  ports:
    # Note: services rely on the name of this port. Do not change it without changing
    # all references to it.
    - name: postgres-port
      port: 5432
      protocol: "TCP"
      targetPort: 5432
    # Note: services rely on the name of this port. Do not change it without changing
    # all references to it.
    - name: hms
      port: 9083
      protocol: "TCP"
      targetPort: 9083
    # Note: services rely on the name of this port. Do not change it without changing
    # all references to it.
    - name: sentry
      port: 30911
      protocol: "TCP"
      targetPort: 30911
  selector:
    run: cerebro-catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebro-catalog
  labels:
    run: cerebro-catalog
  
spec:
  selector:
    matchLabels:
      run: cerebro-catalog
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/02-config.yaml") . | sha256sum }}
        configHash: ""
        {{ if .Values.pod.annotations }}
        {{- .Values.pod.annotations | toYaml  | nindent 8}} 
        {{ end }}
      labels:
        run: cerebro-catalog
    spec:
      serviceAccountName: {{ .Values.serviceaccount.name | default "default" }}
      automountServiceAccountToken: true
      containers:
      - image: {{ .Values.image.repository }}/cdas:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: catalog
        ports:
        # Note: services rely on the name of this port. Do not change it without changing
        # all references to it.
        - containerPort: 5005
          protocol: TCP
          name: "log-server"
        # Note: services rely on the name of this port. Do not change it without changing
        # all references to it.
        - containerPort: 5432
          protocol: TCP
          name: "postgres-port"
        # Note: services rely on the name of this port. Do not change it without changing
        # all references to it.
        - containerPort: 9083
          protocol: TCP
          name: "hms"
        # Note: services rely on the name of this port. Do not change it without changing
        # all references to it.
        - containerPort: 30911
          protocol: TCP
          name: "sentry"
        livenessProbe:
          exec:
            command:
              - /opt/catalog-healthcheck.sh
              - liveness
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 15
        readinessProbe:
          exec:
            command:
              - /opt/catalog-healthcheck.sh
              - readiness
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 15
        envFrom:
        - configMapRef:
            name: default-odas-config
        - configMapRef:
            name: odas-config
        env:
        - name: RESTART_VERSION_0
          value: "1"
        - name: CATALOG_ONLY
          value: "1"
        - name: WATCHER_PREFIX
          value: "catalog"
        volumeMounts:
        - mountPath: /etc/secrets
          name: secrets
          readOnly: true
        - mountPath: /var/lib/okera
          name: okera-lib
        - mountPath: /var/log/okera
          name: okera-log
{{ if .Values.extraVolumeMounts }}
{{- .Values.extraVolumeMounts | toYaml  | nindent 8}} 
{{ end }}          
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: secrets
      - name: okera-lib
        hostPath:
          path: /var/lib/okera
          type: DirectoryOrCreate
      - name: okera-log
        hostPath:
          path: /var/log/okera
          type: DirectoryOrCreate
{{ if .Values.extraVolumes }}
{{- .Values.extraVolumes | toYaml  | nindent 6}} 
{{ end }}
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
{{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
{{- end }}
