apiVersion: v1
kind: Service
metadata:
  name: presto-internal
spec:
  selector:
    presto: coordinator
  ports:
    - name: internal
      port: 8080
      targetPort: 8081
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: presto-coordinator
  labels:
    presto: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      presto: coordinator
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/02-config.yaml") . | sha256sum }}      
        configHash: ""
        {{ if .Values.pod.annotations }}
        {{- .Values.pod.annotations | toYaml  | nindent 8}} 
        {{ end }}
      labels:
        presto: coordinator
    spec:
      serviceAccountName: {{ .Values.serviceaccount.name | default "default" }}
      automountServiceAccountToken: true
      containers:
      - image: {{ .Values.image.repository }}/presto:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: presto-coordinator
        command:
        - sh
        - -c
        - "/opt/watcher.py \"entrypoint.sh coordinator\""
        ports:
        # Note: services rely on the name of this port. Do not change it without changing
        # all references to it.
        - containerPort: 8049
          name: api
        livenessProbe:
          exec:
            command:
              - /usr/local/bin/healthcheck.sh
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
              - /usr/local/bin/healthcheck.sh
          initialDelaySeconds: 5
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: default-odas-config
        - configMapRef:
            name: odas-config
        env:
        - name: RESTART_VERSION_0
          value: "1"
        - name: WATCHER_PREFIX
          value: "presto-coordinator"
        - name: OKERA_ALLOW_IMPERSONATION
          value: "true"
        - name: OKERA_ANALYTICS_CLUSTER
          value: "true"
        - name: DISABLE_RECORDSERVICE_CATALOG
          value: "true"
        - name: OKERA_PRESTO_USE_LOCAL_WORKERS
          value: "true"
        volumeMounts:
        - mountPath: /etc/secrets
          name: secrets
          readOnly: true
        - mountPath: /var/lib/okera
          name: okera-lib
        - mountPath: /var/log/okera
          name: okera-log
{{ if .Values.extraVolumeMounts }}
{{- .Values.extraVolumeMounts | toYaml  | nindent 8}} 
{{ end }}          
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: secrets
      - name: okera-lib
        hostPath:
          path: /var/lib/okera
          type: DirectoryOrCreate
      - name: okera-log
        hostPath:
          path: /var/log/okera
          type: DirectoryOrCreate
{{ if .Values.extraVolumes }}
{{- .Values.extraVolumes | toYaml  | nindent 6}} 
{{ end }}          
      terminationGracePeriodSeconds: 5
{{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
{{- end }}      
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    presto: worker
  name: presto-worker
spec:
  selector:
    matchLabels:
      presto: worker
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/02-config.yaml") . | sha256sum }}      
        configHash: ""
      labels:
        presto: worker
    spec:
      serviceAccountName: {{ .Values.serviceaccount.name | default "default" }}
      automountServiceAccountToken: true
      containers:
      - image: {{ .Values.image.repository }}/presto:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: presto-worker
        command:
        - sh
        - -c
        - "/opt/watcher.py \"entrypoint.sh worker\""
        ports:
        # Note: services rely on the name of this port. Do not change it without changing
        # all references to it.
        - containerPort: 8080
          name: prestoworker
        envFrom:
        - configMapRef:
            name: default-odas-config
        - configMapRef:
            name: odas-config
        env:
        - name: RESTART_VERSION_0
          value: "1"
        - name: WATCHER_PREFIX
          value: "presto-worker"
        - name: OKERA_ALLOW_IMPERSONATION
          value: "true"
        - name: OKERA_ANALYTICS_CLUSTER
          value: "true"
        - name: OKERA_PRESTO_USE_LOCAL_WORKERS
          value: "true"
        - name: MY_HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        volumeMounts:
        - mountPath: /etc/secrets
          name: secrets
          readOnly: true
        - mountPath: /var/lib/okera
          name: okera-lib
        - mountPath: /var/log/okera
          name: okera-log
{{ if .Values.extraVolumeMounts }}
{{- .Values.extraVolumeMounts | toYaml  | nindent 8}} 
{{ end }}
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: secrets
      - name: okera-lib
        hostPath:
          path: /var/lib/okera
          type: DirectoryOrCreate
      - name: okera-log
        hostPath:
          path: /var/log/okera
          type: DirectoryOrCreate
{{ if .Values.extraVolumes }}
{{- .Values.extraVolumes | toYaml  | nindent 6}} 
{{ end }}          
      terminationGracePeriodSeconds: 5
{{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
{{- end }}      
