apiVersion: v1
kind: Service
metadata:
  name: odas-identity-server
  labels:
    run: odas-identity-server
spec:
  type: ClusterIP
  selector:
    run: odas-identity-server
  ports:
    # Note: services rely on the name of this port. Do not change it without changing
    # all references to it.
    - name: api
      port: 8060
      targetPort: 8060
      protocol: "TCP"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odas-identity-server
  labels:
    run: odas-identity-server
spec:
  selector:
    matchLabels:
      run: odas-identity-server
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/02-config.yaml") . | sha256sum }}      
        configHash: ""
        {{ if .Values.pod.annotations }}
        {{- .Values.pod.annotations | toYaml  | nindent 8}} 
        {{ end }}        
      labels:
        run: odas-identity-server
    spec:
      serviceAccountName: {{ .Values.serviceaccount.name | default "default" }}
      automountServiceAccountToken: true
      containers:
      - image: {{ .Values.image.repository }}/odas-identity-server:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: []
        name: odas-identity-server
        ports:
        # Note: services rely on the name of this port. Do not change it without changing
        # all references to it.
        - containerPort: 8060
          protocol: TCP
          name: "api"
        livenessProbe:
          exec:
            command:
              - /opt/identityserver-healthcheck.sh
          initialDelaySeconds: 60
          periodSeconds: 60
        readinessProbe:
          exec:
            command:
              - /opt/identityserver-healthcheck.sh
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "100Mi"
          limits:
            memory: "1Gi"
        envFrom:
        - configMapRef:
            name: default-odas-config
        - configMapRef:
            name: odas-config
        env:
        - name: RESTART_VERSION_0
          value: "1"
        - name: WATCHER_PREFIX
          value: "identity"
        volumeMounts:
        - mountPath: /etc/secrets
          name: secrets
          readOnly: true
        - mountPath: /var/lib/okera
          name: okera-lib
        - mountPath: /var/log/okera
          name: okera-log
{{ if .Values.extraVolumeMounts }}
{{- .Values.extraVolumeMounts | toYaml  | nindent 8}} 
{{ end }}
      volumes:
      - name: secrets
        secret:
          defaultMode: 420
          secretName: secrets
      - name: okera-lib
        hostPath:
          path: /var/lib/okera
          type: DirectoryOrCreate
      - name: okera-log
        hostPath:
          path: /var/log/okera
          type: DirectoryOrCreate
{{ if .Values.extraVolumes }}
{{- .Values.extraVolumes | toYaml  | nindent 6}} 
{{ end }}            
      terminationGracePeriodSeconds: 5
{{- if .Values.nodeSelector }}
      nodeSelector: {{- .Values.nodeSelector | toYaml | nindent 8 }}
{{- end }}